//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DataAccess.Entities
{

	/// <summary>
	/// 实体类CmsTitleTitlePartRecord 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Cms_Title.TitlePartRecord","PP")]
	[Serializable]
	public partial class CmsTitleTitlePartRecord : Entity 
	{
		#region Model
		private int _Id;
		private int? _ContentItemRecord_id;
		private string _Title;
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ContentItemRecord_id
		{
			get{ return _ContentItemRecord_id; }
			set
			{
				this.OnPropertyValueChange(_.ContentItemRecord_id,_ContentItemRecord_id,value);
				this._ContentItemRecord_id=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.ContentItemRecord_id,
				_.Title};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._ContentItemRecord_id,
				this._Title};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Cms_Title.TitlePartRecord");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Cms_Title.TitlePartRecord","Id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ContentItemRecord_id = new Field("ContentItemRecord_id","Cms_Title.TitlePartRecord","ContentItemRecord_id");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title","Cms_Title.TitlePartRecord","Title");
		}
		#endregion


	}
}

