//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Support: http://www.cnblogs.com/huxj
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace DataAccess.Entities
{
    /// <summary>
    /// 如果前端不需要Test1、Test2、Test3这三个字段，可以建立此ViewModel。
    /// </summary>
    public class TableMysql_Page1
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string IDNumber { get; set; }
        public string MobilPhone { get; set; }
        public DateTime CreateTime { get; set; }
    }
    /// <summary>
    /// 同张表可以建立多个ViewModel，以适应不同页面不同列数。
    /// </summary>
    public class TableMysql_Page2
    {

    }
}

