//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace OAA.DataAccess.Entities
{
    /// <summary>
    /// 实体类BizHouse。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Biz_House")]
    [Serializable]
    public partial class BizHouse : Entity
    {
        #region Model
		private Guid _Id;
		private string _Number;
		private string _Name;
		private decimal? _Price;
		private int? _PriceType;
		private string _PriceTypeValue;
		private int? _Country;
		private string _CountryValue;
		private int? _Province;
		private string _ProvinceValue;
		private int? _City;
		private string _CityValue;
		private string _Address;
		private int? _HouseType;
		private string _HouseTypeValue;
		private int? _HouseParlor;
		private string _HouseParlorValue;
		private decimal? _Area;
		private decimal? _Age;
		private int? _Aspect;
		private string _AspectValue;
		private int? _HouseClass;
		private string _HouseClassValue;
		private string _Infomation;
		private string _Preview;
		private bool _IsRecommend;
		private int _State;
		private DateTime _CreateTime;
		private string _MapPreview;
		private string _MapCoords;

		/// <summary>
		/// 
		/// </summary>
		public Guid Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
        /// <summary>
        /// 
        /// </summary>
        [Field("Number")]
        public string Number2
		{
			get{ return _Number; }
			set
			{
				this.OnPropertyValueChange("Number");
				this._Number = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
        [Field("Name")]
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange("Name");
				this._Name = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Price
		{
			get{ return _Price; }
			set
			{
				this.OnPropertyValueChange("Price");
				this._Price = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? PriceType
		{
			get{ return _PriceType; }
			set
			{
				this.OnPropertyValueChange("PriceType");
				this._PriceType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PriceTypeValue
		{
			get{ return _PriceTypeValue; }
			set
			{
				this.OnPropertyValueChange("PriceTypeValue");
				this._PriceTypeValue = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Country
		{
			get{ return _Country; }
			set
			{
				this.OnPropertyValueChange("Country");
				this._Country = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CountryValue
		{
			get{ return _CountryValue; }
			set
			{
				this.OnPropertyValueChange("CountryValue");
				this._CountryValue = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Province
		{
			get{ return _Province; }
			set
			{
				this.OnPropertyValueChange("Province");
				this._Province = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ProvinceValue
		{
			get{ return _ProvinceValue; }
			set
			{
				this.OnPropertyValueChange("ProvinceValue");
				this._ProvinceValue = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? City
		{
			get{ return _City; }
			set
			{
				this.OnPropertyValueChange("City");
				this._City = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CityValue
		{
			get{ return _CityValue; }
			set
			{
				this.OnPropertyValueChange("CityValue");
				this._CityValue = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Address
		{
			get{ return _Address; }
			set
			{
				this.OnPropertyValueChange("Address");
				this._Address = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? HouseType
		{
			get{ return _HouseType; }
			set
			{
				this.OnPropertyValueChange("HouseType");
				this._HouseType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string HouseTypeValue
		{
			get{ return _HouseTypeValue; }
			set
			{
				this.OnPropertyValueChange("HouseTypeValue");
				this._HouseTypeValue = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? HouseParlor
		{
			get{ return _HouseParlor; }
			set
			{
				this.OnPropertyValueChange("HouseParlor");
				this._HouseParlor = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string HouseParlorValue
		{
			get{ return _HouseParlorValue; }
			set
			{
				this.OnPropertyValueChange("HouseParlorValue");
				this._HouseParlorValue = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Area
		{
			get{ return _Area; }
			set
			{
				this.OnPropertyValueChange("Area");
				this._Area = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Age
		{
			get{ return _Age; }
			set
			{
				this.OnPropertyValueChange("Age");
				this._Age = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Aspect
		{
			get{ return _Aspect; }
			set
			{
				this.OnPropertyValueChange("Aspect");
				this._Aspect = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AspectValue
		{
			get{ return _AspectValue; }
			set
			{
				this.OnPropertyValueChange("AspectValue");
				this._AspectValue = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? HouseClass
		{
			get{ return _HouseClass; }
			set
			{
				this.OnPropertyValueChange("HouseClass");
				this._HouseClass = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string HouseClassValue
		{
			get{ return _HouseClassValue; }
			set
			{
				this.OnPropertyValueChange("HouseClassValue");
				this._HouseClassValue = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Infomation
		{
			get{ return _Infomation; }
			set
			{
				this.OnPropertyValueChange("Infomation");
				this._Infomation = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Preview
		{
			get{ return _Preview; }
			set
			{
				this.OnPropertyValueChange("Preview");
				this._Preview = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool IsRecommend
		{
			get{ return _IsRecommend; }
			set
			{
				this.OnPropertyValueChange("IsRecommend");
				this._IsRecommend = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange("State");
				this._State = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange("CreateTime");
				this._CreateTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MapPreview
		{
			get{ return _MapPreview; }
			set
			{
				this.OnPropertyValueChange("MapPreview");
				this._MapPreview = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MapCoords
		{
			get{ return _MapCoords; }
			set
			{
				this.OnPropertyValueChange("MapCoords");
				this._MapCoords = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.Number2,
				_.Name,
				_.Price,
				_.PriceType,
				_.PriceTypeValue,
				_.Country,
				_.CountryValue,
				_.Province,
				_.ProvinceValue,
				_.City,
				_.CityValue,
				_.Address,
				_.HouseType,
				_.HouseTypeValue,
				_.HouseParlor,
				_.HouseParlorValue,
				_.Area,
				_.Age,
				_.Aspect,
				_.AspectValue,
				_.HouseClass,
				_.HouseClassValue,
				_.Infomation,
				_.Preview,
				_.IsRecommend,
				_.State,
				_.CreateTime,
				_.MapPreview,
				_.MapCoords,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._Number,
				this._Name,
				this._Price,
				this._PriceType,
				this._PriceTypeValue,
				this._Country,
				this._CountryValue,
				this._Province,
				this._ProvinceValue,
				this._City,
				this._CityValue,
				this._Address,
				this._HouseType,
				this._HouseTypeValue,
				this._HouseParlor,
				this._HouseParlorValue,
				this._Area,
				this._Age,
				this._Aspect,
				this._AspectValue,
				this._HouseClass,
				this._HouseClassValue,
				this._Infomation,
				this._Preview,
				this._IsRecommend,
				this._State,
				this._CreateTime,
				this._MapPreview,
				this._MapCoords,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Biz_House");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Number2 = new Field("Number", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Price = new Field("Price", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PriceType = new Field("PriceType", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PriceTypeValue = new Field("PriceTypeValue", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Country = new Field("Country", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CountryValue = new Field("CountryValue", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Province = new Field("Province", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProvinceValue = new Field("ProvinceValue", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field City = new Field("City", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CityValue = new Field("CityValue", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Address = new Field("Address", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HouseType = new Field("HouseType", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HouseTypeValue = new Field("HouseTypeValue", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HouseParlor = new Field("HouseParlor", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HouseParlorValue = new Field("HouseParlorValue", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Area = new Field("Area", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Age = new Field("Age", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Aspect = new Field("Aspect", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AspectValue = new Field("AspectValue", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HouseClass = new Field("HouseClass", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HouseClassValue = new Field("HouseClassValue", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Infomation = new Field("Infomation", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Preview = new Field("Preview", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IsRecommend = new Field("IsRecommend", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MapPreview = new Field("MapPreview", "Biz_House", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MapCoords = new Field("MapCoords", "Biz_House", "");
        }
        #endregion
	}
}