//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Dos.ORM;

namespace Polymerch.DataModel
{
    public partial class BizReview
    {
        public List<BizReview> ChildList { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Avatar { get; set; }
    }
    /// <summary>
    /// 实体类BizReview。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Biz_Review")]
    [Serializable]
    public partial class BizReview : Entity
    {
        #region Model
		private Guid _Id;
		private Guid _FkId;
		private Guid? _ParentId;
		private string _Content;
		private int _Helpful;
		private Guid? _UserId;
		private decimal _Score;
		private int _State;
		private DateTime _CreateTime;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public Guid Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("FkId")]
		public Guid FkId
		{
			get{ return _FkId; }
			set
			{
				this.OnPropertyValueChange("FkId");
				this._FkId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ParentId")]
		public Guid? ParentId
		{
			get{ return _ParentId; }
			set
			{
				this.OnPropertyValueChange("ParentId");
				this._ParentId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Content")]
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange("Content");
				this._Content = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Helpful")]
		public int Helpful
		{
			get{ return _Helpful; }
			set
			{
				this.OnPropertyValueChange("Helpful");
				this._Helpful = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("UserId")]
		public Guid? UserId
		{
			get{ return _UserId; }
			set
			{
				this.OnPropertyValueChange("UserId");
				this._UserId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Score")]
		public decimal Score
		{
			get{ return _Score; }
			set
			{
				this.OnPropertyValueChange("Score");
				this._Score = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("State")]
		public int State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange("State");
				this._State = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreateTime")]
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange("CreateTime");
				this._CreateTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
				_.FkId,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.FkId,
				_.ParentId,
				_.Content,
				_.Helpful,
				_.UserId,
				_.Score,
				_.State,
				_.CreateTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._FkId,
				this._ParentId,
				this._Content,
				this._Helpful,
				this._UserId,
				this._Score,
				this._State,
				this._CreateTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Biz_Review");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Biz_Review", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FkId = new Field("FkId", "Biz_Review", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ParentId = new Field("ParentId", "Biz_Review", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Content = new Field("Content", "Biz_Review", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Helpful = new Field("Helpful", "Biz_Review", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserId = new Field("UserId", "Biz_Review", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Score = new Field("Score", "Biz_Review", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State", "Biz_Review", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "Biz_Review", "");
        }
        #endregion
	}
}