//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Model
{

	/// <summary>
	/// 实体类CmsNews 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("Cms_News")]
	[Serializable]
	public partial class CmsNews : Entity 
	{
		#region Model
		private Guid _Id;
		private string _Title;
		private string _Number;
		private string _Summary;
		private string _Code;
		private string _AllCode;
		private string _Url;
		private string _Content;
		private string _Source;
		private int _Hits;
		private string _Preview;
		private int _State;
		private string _Keywords;
		private string _Description;
		private DateTime _PublishTime;
		private DateTime _CreateTime;
		/// <summary>
		/// 
		/// </summary>
		public Guid Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange(_.Id,_Id,value);
				this._Id=value;
			}
		}
		/// <summary>
		/// 标题
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
        /// <summary>
        /// 
        /// </summary>
        [Field("Number")]
        public string No
		{
			get{ return _Number; }
			set
			{
				this.OnPropertyValueChange(_.No,_Number,value);
				this._Number=value;
			}
		}
		/// <summary>
		/// 摘要
		/// </summary>
		public string Summary
		{
			get{ return _Summary; }
			set
			{
				this.OnPropertyValueChange(_.Summary,_Summary,value);
				this._Summary=value;
			}
		}
		/// <summary>
		/// 类别
		/// </summary>
		public string Code
		{
			get{ return _Code; }
			set
			{
				this.OnPropertyValueChange(_.Code,_Code,value);
				this._Code=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string AllCode
		{
			get{ return _AllCode; }
			set
			{
				this.OnPropertyValueChange(_.AllCode,_AllCode,value);
				this._AllCode=value;
			}
		}
		/// <summary>
		/// 自定义链接
		/// </summary>
		public string Url
		{
			get{ return _Url; }
			set
			{
				this.OnPropertyValueChange(_.Url,_Url,value);
				this._Url=value;
			}
		}
		/// <summary>
		/// 内容
		/// </summary>
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange(_.Content,_Content,value);
				this._Content=value;
			}
		}
		/// <summary>
		/// 来源
		/// </summary>
		public string Source
		{
			get{ return _Source; }
			set
			{
				this.OnPropertyValueChange(_.Source,_Source,value);
				this._Source=value;
			}
		}
		/// <summary>
		/// 点击数/浏览数
		/// </summary>
		public int Hits
		{
			get{ return _Hits; }
			set
			{
				this.OnPropertyValueChange(_.Hits,_Hits,value);
				this._Hits=value;
			}
		}
		/// <summary>
		/// 预览图
		/// </summary>
		public string Preview
		{
			get{ return _Preview; }
			set
			{
				this.OnPropertyValueChange(_.Preview,_Preview,value);
				this._Preview=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange(_.State,_State,value);
				this._State=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Keywords
		{
			get{ return _Keywords; }
			set
			{
				this.OnPropertyValueChange(_.Keywords,_Keywords,value);
				this._Keywords=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Description
		{
			get{ return _Description; }
			set
			{
				this.OnPropertyValueChange(_.Description,_Description,value);
				this._Description=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime PublishTime
		{
			get{ return _PublishTime; }
			set
			{
				this.OnPropertyValueChange(_.PublishTime,_PublishTime,value);
				this._PublishTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Id};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Id,
				_.Title,
				_.No,
				_.Summary,
				_.Code,
				_.AllCode,
				_.Url,
				_.Content,
				_.Source,
				_.Hits,
				_.Preview,
				_.State,
				_.Keywords,
				_.Description,
				_.PublishTime,
				_.CreateTime};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Id,
				this._Title,
				this._Number,
				this._Summary,
				this._Code,
				this._AllCode,
				this._Url,
				this._Content,
				this._Source,
				this._Hits,
				this._Preview,
				this._State,
				this._Keywords,
				this._Description,
				this._PublishTime,
				this._CreateTime};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Cms_News");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id","Cms_News","Id");
			/// <summary>
			/// 标题
			/// </summary>
			public readonly static Field Title = new Field("Title","Cms_News","标题");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field No = new Field("Number","Cms_News","Number");
			/// <summary>
			/// 摘要
			/// </summary>
			public readonly static Field Summary = new Field("Summary","Cms_News","摘要");
			/// <summary>
			/// 类别
			/// </summary>
			public readonly static Field Code = new Field("Code","Cms_News","类别");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field AllCode = new Field("AllCode","Cms_News","AllCode");
			/// <summary>
			/// 自定义链接
			/// </summary>
			public readonly static Field Url = new Field("Url","Cms_News","自定义链接");
			/// <summary>
			/// 内容
			/// </summary>
			public readonly static Field Content = new Field("Content","Cms_News","内容");
			/// <summary>
			/// 来源
			/// </summary>
			public readonly static Field Source = new Field("Source","Cms_News","来源");
			/// <summary>
			/// 点击数/浏览数
			/// </summary>
			public readonly static Field Hits = new Field("Hits","Cms_News","点击数/浏览数");
			/// <summary>
			/// 预览图
			/// </summary>
			public readonly static Field Preview = new Field("Preview","Cms_News","预览图");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State","Cms_News","State");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Keywords = new Field("Keywords","Cms_News","Keywords");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Description = new Field("Description","Cms_News","Description");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PublishTime = new Field("PublishTime","Cms_News","PublishTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","Cms_News","CreateTime");
		}
		#endregion


	}
}

