//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace ITdos.Project.DataModel
{
    /// <summary>
    /// 实体类Hmaccounts。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("hm_accounts")]
    [Serializable]
    public partial class Hmaccounts : Entity
    {
        #region Model
        private int _Accountid;
        private int _Accountdomainid;
        private int _Accountadminlevel;
        private string _Accountaddress;
        private string _Accountpassword;
        private int _Accountactive;
        private int _Accountisad;
        private string _Accountaddomain;
        private string _Accountadusername;
        private int _Accountmaxsize;
        private int _Accountvacationmessageon;
        private string _Accountvacationmessage;
        private string _Accountvacationsubject;
        private int _Accountpwencryption;
        private int _Accountforwardenabled;
        private string _Accountforwardaddress;
        private int _Accountforwardkeeporiginal;
        private int _Accountenablesignature;
        private string _Accountsignatureplaintext;
        private string _Accountsignaturehtml;
        private DateTime _Accountlastlogontime;
        private int _Accountvacationexpires;
        private DateTime _Accountvacationexpiredate;
        private string _Accountpersonfirstname;
        private string _Accountpersonlastname;

        /// <summary>
        /// 
        /// </summary>
        [Field("accountid")]
        public int Accountid
        {
            get { return _Accountid; }
            set
            {
                this.OnPropertyValueChange("accountid");
                this._Accountid = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountdomainid")]
        public int Accountdomainid
        {
            get { return _Accountdomainid; }
            set
            {
                this.OnPropertyValueChange("accountdomainid");
                this._Accountdomainid = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountadminlevel")]
        public int Accountadminlevel
        {
            get { return _Accountadminlevel; }
            set
            {
                this.OnPropertyValueChange("accountadminlevel");
                this._Accountadminlevel = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountaddress")]
        public string Accountaddress
        {
            get { return _Accountaddress; }
            set
            {
                this.OnPropertyValueChange("accountaddress");
                this._Accountaddress = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountpassword")]
        public string Accountpassword
        {
            get { return _Accountpassword; }
            set
            {
                this.OnPropertyValueChange("accountpassword");
                this._Accountpassword = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountactive")]
        public int Accountactive
        {
            get { return _Accountactive; }
            set
            {
                this.OnPropertyValueChange("accountactive");
                this._Accountactive = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountisad")]
        public int Accountisad
        {
            get { return _Accountisad; }
            set
            {
                this.OnPropertyValueChange("accountisad");
                this._Accountisad = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountaddomain")]
        public string Accountaddomain
        {
            get { return _Accountaddomain; }
            set
            {
                this.OnPropertyValueChange("accountaddomain");
                this._Accountaddomain = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountadusername")]
        public string Accountadusername
        {
            get { return _Accountadusername; }
            set
            {
                this.OnPropertyValueChange("accountadusername");
                this._Accountadusername = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountmaxsize")]
        public int Accountmaxsize
        {
            get { return _Accountmaxsize; }
            set
            {
                this.OnPropertyValueChange("accountmaxsize");
                this._Accountmaxsize = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountvacationmessageon")]
        public int Accountvacationmessageon
        {
            get { return _Accountvacationmessageon; }
            set
            {
                this.OnPropertyValueChange("accountvacationmessageon");
                this._Accountvacationmessageon = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountvacationmessage")]
        public string Accountvacationmessage
        {
            get { return _Accountvacationmessage; }
            set
            {
                this.OnPropertyValueChange("accountvacationmessage");
                this._Accountvacationmessage = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountvacationsubject")]
        public string Accountvacationsubject
        {
            get { return _Accountvacationsubject; }
            set
            {
                this.OnPropertyValueChange("accountvacationsubject");
                this._Accountvacationsubject = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountpwencryption")]
        public int Accountpwencryption
        {
            get { return _Accountpwencryption; }
            set
            {
                this.OnPropertyValueChange("accountpwencryption");
                this._Accountpwencryption = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountforwardenabled")]
        public int Accountforwardenabled
        {
            get { return _Accountforwardenabled; }
            set
            {
                this.OnPropertyValueChange("accountforwardenabled");
                this._Accountforwardenabled = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountforwardaddress")]
        public string Accountforwardaddress
        {
            get { return _Accountforwardaddress; }
            set
            {
                this.OnPropertyValueChange("accountforwardaddress");
                this._Accountforwardaddress = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountforwardkeeporiginal")]
        public int Accountforwardkeeporiginal
        {
            get { return _Accountforwardkeeporiginal; }
            set
            {
                this.OnPropertyValueChange("accountforwardkeeporiginal");
                this._Accountforwardkeeporiginal = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountenablesignature")]
        public int Accountenablesignature
        {
            get { return _Accountenablesignature; }
            set
            {
                this.OnPropertyValueChange("accountenablesignature");
                this._Accountenablesignature = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountsignatureplaintext")]
        public string Accountsignatureplaintext
        {
            get { return _Accountsignatureplaintext; }
            set
            {
                this.OnPropertyValueChange("accountsignatureplaintext");
                this._Accountsignatureplaintext = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountsignaturehtml")]
        public string Accountsignaturehtml
        {
            get { return _Accountsignaturehtml; }
            set
            {
                this.OnPropertyValueChange("accountsignaturehtml");
                this._Accountsignaturehtml = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountlastlogontime")]
        public DateTime Accountlastlogontime
        {
            get { return _Accountlastlogontime; }
            set
            {
                this.OnPropertyValueChange("accountlastlogontime");
                this._Accountlastlogontime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountvacationexpires")]
        public int Accountvacationexpires
        {
            get { return _Accountvacationexpires; }
            set
            {
                this.OnPropertyValueChange("accountvacationexpires");
                this._Accountvacationexpires = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountvacationexpiredate")]
        public DateTime Accountvacationexpiredate
        {
            get { return _Accountvacationexpiredate; }
            set
            {
                this.OnPropertyValueChange("accountvacationexpiredate");
                this._Accountvacationexpiredate = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountpersonfirstname")]
        public string Accountpersonfirstname
        {
            get { return _Accountpersonfirstname; }
            set
            {
                this.OnPropertyValueChange("accountpersonfirstname");
                this._Accountpersonfirstname = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("accountpersonlastname")]
        public string Accountpersonlastname
        {
            get { return _Accountpersonlastname; }
            set
            {
                this.OnPropertyValueChange("accountpersonlastname");
                this._Accountpersonlastname = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Accountid,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Accountid;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Accountid,
                _.Accountdomainid,
                _.Accountadminlevel,
                _.Accountaddress,
                _.Accountpassword,
                _.Accountactive,
                _.Accountisad,
                _.Accountaddomain,
                _.Accountadusername,
                _.Accountmaxsize,
                _.Accountvacationmessageon,
                _.Accountvacationmessage,
                _.Accountvacationsubject,
                _.Accountpwencryption,
                _.Accountforwardenabled,
                _.Accountforwardaddress,
                _.Accountforwardkeeporiginal,
                _.Accountenablesignature,
                _.Accountsignatureplaintext,
                _.Accountsignaturehtml,
                _.Accountlastlogontime,
                _.Accountvacationexpires,
                _.Accountvacationexpiredate,
                _.Accountpersonfirstname,
                _.Accountpersonlastname,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Accountid,
                this._Accountdomainid,
                this._Accountadminlevel,
                this._Accountaddress,
                this._Accountpassword,
                this._Accountactive,
                this._Accountisad,
                this._Accountaddomain,
                this._Accountadusername,
                this._Accountmaxsize,
                this._Accountvacationmessageon,
                this._Accountvacationmessage,
                this._Accountvacationsubject,
                this._Accountpwencryption,
                this._Accountforwardenabled,
                this._Accountforwardaddress,
                this._Accountforwardkeeporiginal,
                this._Accountenablesignature,
                this._Accountsignatureplaintext,
                this._Accountsignaturehtml,
                this._Accountlastlogontime,
                this._Accountvacationexpires,
                this._Accountvacationexpiredate,
                this._Accountpersonfirstname,
                this._Accountpersonlastname,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "hm_accounts");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountid = new Field("accountid", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountdomainid = new Field("accountdomainid", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountadminlevel = new Field("accountadminlevel", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountaddress = new Field("accountaddress", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountpassword = new Field("accountpassword", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountactive = new Field("accountactive", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountisad = new Field("accountisad", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountaddomain = new Field("accountaddomain", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountadusername = new Field("accountadusername", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountmaxsize = new Field("accountmaxsize", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountvacationmessageon = new Field("accountvacationmessageon", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountvacationmessage = new Field("accountvacationmessage", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountvacationsubject = new Field("accountvacationsubject", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountpwencryption = new Field("accountpwencryption", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountforwardenabled = new Field("accountforwardenabled", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountforwardaddress = new Field("accountforwardaddress", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountforwardkeeporiginal = new Field("accountforwardkeeporiginal", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountenablesignature = new Field("accountenablesignature", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountsignatureplaintext = new Field("accountsignatureplaintext", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountsignaturehtml = new Field("accountsignaturehtml", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountlastlogontime = new Field("accountlastlogontime", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountvacationexpires = new Field("accountvacationexpires", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountvacationexpiredate = new Field("accountvacationexpiredate", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountpersonfirstname = new Field("accountpersonfirstname", "hm_accounts", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Accountpersonlastname = new Field("accountpersonlastname", "hm_accounts", "");
        }
        #endregion
    }
}