//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Standard.DataModel
{
    /// <summary>
    /// 实体类BizStandardList。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Biz_StandardList")]
    [Serializable]
    public partial class BizStandardList : Entity
    {
        #region Model
		private Guid _Id;
		private string _QAClassA825up;
		private string _QAClassA825;
		private string _QAClassA404up;
		private string _QAClassA404;
		private int _QAHits;
		private int _QAComments;
		private int _QADownloads;
		private int _QAFavorites;
		private decimal _QAPrice;
		private int _QAState;
		private DateTime _QACreateTime;
		private DateTime _QAUpdateTime;
		private int _QATestItemCount;
		private int _STANDARDID;
		private string _STANDCLASS;
		private string _STANDTYPE;
		private string _A100;
		private string _StandPreNo;
		private string _A107;
		private int? _A225;
		private string _STANDSTATUS;
		private string _REFERSTANDNO;
		private string _A825;
		private string _A301;
		private string _A302;
		private string _ADOPTLEVEL;
		private string _ADOPTNO;
		private string _ADOPTDESC;
		private string _DECLAREDATE;
		private string _ISSUEDATE;
		private string _A205;
		private string _MODIDATE;
		private string _A200;
		private string _COMMITTEEDESC;
		private string _SUEDEPART;
		private string _A461;
		private string _A462;
		private string _ISSUEDEPART;
		private string _A404;
		private string _LANGUAGE;
		private int? _PUBLISHSEQ;
		private int _A305;
		private int _HAVEPDF;
		private string _PAPERPUBLISHDATE;
		private decimal _DOWNPRICE;
		private int? _ISCOLOR;
		private int? _COLORPAGENUM;
		private string _BOOKNO;
		private string _PDFDATE;
		private int? _WORDCOUNT;
		private decimal? _PRINTNUMBER;
		private string _FORMAT;
		private string _OWNERDEPT;
		private string _DRAFTSMAN;
		private string _UDCNo;
		private int? _HASMODIFY;
		private string _MODIFYREMARK;
		private string _DRAFTSDEPT;
		private string _READER;
		private string _INTRODUCTION;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public Guid Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("QAClassA825up")]
		public string QAClassA825up
		{
			get{ return _QAClassA825up; }
			set
			{
				this.OnPropertyValueChange("QAClassA825up");
				this._QAClassA825up = value;
			}
		}
		/// <summary>
		/// 中国国家标准CN二级分类
		/// </summary>
		[Field("QAClassA825")]
		public string QAClassA825
		{
			get{ return _QAClassA825; }
			set
			{
				this.OnPropertyValueChange("QAClassA825");
				this._QAClassA825 = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("QAClassA404up")]
		public string QAClassA404up
		{
			get{ return _QAClassA404up; }
			set
			{
				this.OnPropertyValueChange("QAClassA404up");
				this._QAClassA404up = value;
			}
		}
		/// <summary>
		/// 国际标准ISO二级分类
		/// </summary>
		[Field("QAClassA404")]
		public string QAClassA404
		{
			get{ return _QAClassA404; }
			set
			{
				this.OnPropertyValueChange("QAClassA404");
				this._QAClassA404 = value;
			}
		}
		/// <summary>
		/// 点击/预览数
		/// </summary>
		[Field("QAHits")]
		public int QAHits
		{
			get{ return _QAHits; }
			set
			{
				this.OnPropertyValueChange("QAHits");
				this._QAHits = value;
			}
		}
		/// <summary>
		/// 评论数
		/// </summary>
		[Field("QAComments")]
		public int QAComments
		{
			get{ return _QAComments; }
			set
			{
				this.OnPropertyValueChange("QAComments");
				this._QAComments = value;
			}
		}
		/// <summary>
		/// 下载数
		/// </summary>
		[Field("QADownloads")]
		public int QADownloads
		{
			get{ return _QADownloads; }
			set
			{
				this.OnPropertyValueChange("QADownloads");
				this._QADownloads = value;
			}
		}
		/// <summary>
		/// 收藏数
		/// </summary>
		[Field("QAFavorites")]
		public int QAFavorites
		{
			get{ return _QAFavorites; }
			set
			{
				this.OnPropertyValueChange("QAFavorites");
				this._QAFavorites = value;
			}
		}
		/// <summary>
		/// 我们出售的价格
		/// </summary>
		[Field("QAPrice")]
		public decimal QAPrice
		{
			get{ return _QAPrice; }
			set
			{
				this.OnPropertyValueChange("QAPrice");
				this._QAPrice = value;
			}
		}
		/// <summary>
		/// 我们的状态
		/// </summary>
		[Field("QAState")]
		public int QAState
		{
			get{ return _QAState; }
			set
			{
				this.OnPropertyValueChange("QAState");
				this._QAState = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("QACreateTime")]
		public DateTime QACreateTime
		{
			get{ return _QACreateTime; }
			set
			{
				this.OnPropertyValueChange("QACreateTime");
				this._QACreateTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("QAUpdateTime")]
		public DateTime QAUpdateTime
		{
			get{ return _QAUpdateTime; }
			set
			{
				this.OnPropertyValueChange("QAUpdateTime");
				this._QAUpdateTime = value;
			}
		}
		/// <summary>
		/// 检验项目总数
		/// </summary>
		[Field("QATestItemCount")]
		public int QATestItemCount
		{
			get{ return _QATestItemCount; }
			set
			{
				this.OnPropertyValueChange("QATestItemCount");
				this._QATestItemCount = value;
			}
		}
		/// <summary>
		/// 序列号
		/// </summary>
		[Field("STANDARDID")]
		public int STANDARDID
		{
			get{ return _STANDARDID; }
			set
			{
				this.OnPropertyValueChange("STANDARDID");
				this._STANDARDID = value;
			}
		}
		/// <summary>
		/// 标准类型。CN-国家标准、QT-行业标准、GW-国外标准、ISO-国际标准、JJ-计量规程规范
		/// </summary>
		[Field("STANDCLASS")]
		public string STANDCLASS
		{
			get{ return _STANDCLASS; }
			set
			{
				this.OnPropertyValueChange("STANDCLASS");
				this._STANDCLASS = value;
			}
		}
		/// <summary>
		/// 标准属性。STANDCLASS下的二级分类
		/// </summary>
		[Field("STANDTYPE")]
		public string STANDTYPE
		{
			get{ return _STANDTYPE; }
			set
			{
				this.OnPropertyValueChange("STANDTYPE");
				this._STANDTYPE = value;
			}
		}
		/// <summary>
		/// 标准号
		/// </summary>
		[Field("A100")]
		public string A100
		{
			get{ return _A100; }
			set
			{
				this.OnPropertyValueChange("A100");
				this._A100 = value;
			}
		}
		/// <summary>
		/// 标准代号
		/// </summary>
		[Field("StandPreNo")]
		public string StandPreNo
		{
			get{ return _StandPreNo; }
			set
			{
				this.OnPropertyValueChange("StandPreNo");
				this._StandPreNo = value;
			}
		}
		/// <summary>
		/// 标准编号
		/// </summary>
		[Field("A107")]
		public string A107
		{
			get{ return _A107; }
			set
			{
				this.OnPropertyValueChange("A107");
				this._A107 = value;
			}
		}
		/// <summary>
		/// 标准年代号
		/// </summary>
		[Field("A225")]
		public int? A225
		{
			get{ return _A225; }
			set
			{
				this.OnPropertyValueChange("A225");
				this._A225 = value;
			}
		}
		/// <summary>
		/// 标准状态
		/// </summary>
		[Field("STANDSTATUS")]
		public string STANDSTATUS
		{
			get{ return _STANDSTATUS; }
			set
			{
				this.OnPropertyValueChange("STANDSTATUS");
				this._STANDSTATUS = value;
			}
		}
		/// <summary>
		/// 引用标准号
		/// </summary>
		[Field("REFERSTANDNO")]
		public string REFERSTANDNO
		{
			get{ return _REFERSTANDNO; }
			set
			{
				this.OnPropertyValueChange("REFERSTANDNO");
				this._REFERSTANDNO = value;
			}
		}
		/// <summary>
		/// 中标分类号
		/// </summary>
		[Field("A825")]
		public string A825
		{
			get{ return _A825; }
			set
			{
				this.OnPropertyValueChange("A825");
				this._A825 = value;
			}
		}
		/// <summary>
		/// 中文名称
		/// </summary>
		[Field("A301")]
		public string A301
		{
			get{ return _A301; }
			set
			{
				this.OnPropertyValueChange("A301");
				this._A301 = value;
			}
		}
		/// <summary>
		/// 英文名称
		/// </summary>
		[Field("A302")]
		public string A302
		{
			get{ return _A302; }
			set
			{
				this.OnPropertyValueChange("A302");
				this._A302 = value;
			}
		}
		/// <summary>
		/// 采标程度
		/// </summary>
		[Field("ADOPTLEVEL")]
		public string ADOPTLEVEL
		{
			get{ return _ADOPTLEVEL; }
			set
			{
				this.OnPropertyValueChange("ADOPTLEVEL");
				this._ADOPTLEVEL = value;
			}
		}
		/// <summary>
		/// 采标号
		/// </summary>
		[Field("ADOPTNO")]
		public string ADOPTNO
		{
			get{ return _ADOPTNO; }
			set
			{
				this.OnPropertyValueChange("ADOPTNO");
				this._ADOPTNO = value;
			}
		}
		/// <summary>
		/// 采标名称
		/// </summary>
		[Field("ADOPTDESC")]
		public string ADOPTDESC
		{
			get{ return _ADOPTDESC; }
			set
			{
				this.OnPropertyValueChange("ADOPTDESC");
				this._ADOPTDESC = value;
			}
		}
		/// <summary>
		/// 公告日期
		/// </summary>
		[Field("DECLAREDATE")]
		public string DECLAREDATE
		{
			get{ return _DECLAREDATE; }
			set
			{
				this.OnPropertyValueChange("DECLAREDATE");
				this._DECLAREDATE = value;
			}
		}
		/// <summary>
		/// 首发日期.原来的发布日期等于现在的首发日期
		/// </summary>
		[Field("ISSUEDATE")]
		public string ISSUEDATE
		{
			get{ return _ISSUEDATE; }
			set
			{
				this.OnPropertyValueChange("ISSUEDATE");
				this._ISSUEDATE = value;
			}
		}
		/// <summary>
		/// 实施日期.原来的修订日期等于现在的发布日期
		/// </summary>
		[Field("A205")]
		public string A205
		{
			get{ return _A205; }
			set
			{
				this.OnPropertyValueChange("A205");
				this._A205 = value;
			}
		}
		/// <summary>
		/// 发布日期.1900-1-1表示空的
		/// </summary>
		[Field("MODIDATE")]
		public string MODIDATE
		{
			get{ return _MODIDATE; }
			set
			{
				this.OnPropertyValueChange("MODIDATE");
				this._MODIDATE = value;
			}
		}
		/// <summary>
		/// 作废标记.0表示未作废
		/// </summary>
		[Field("A200")]
		public string A200
		{
			get{ return _A200; }
			set
			{
				this.OnPropertyValueChange("A200");
				this._A200 = value;
			}
		}
		/// <summary>
		/// 标准化技术委员会.即归口单位
		/// </summary>
		[Field("COMMITTEEDESC")]
		public string COMMITTEEDESC
		{
			get{ return _COMMITTEEDESC; }
			set
			{
				this.OnPropertyValueChange("COMMITTEEDESC");
				this._COMMITTEEDESC = value;
			}
		}
		/// <summary>
		/// 提出部门
		/// </summary>
		[Field("SUEDEPART")]
		public string SUEDEPART
		{
			get{ return _SUEDEPART; }
			set
			{
				this.OnPropertyValueChange("SUEDEPART");
				this._SUEDEPART = value;
			}
		}
		/// <summary>
		/// 代替标准
		/// </summary>
		[Field("A461")]
		public string A461
		{
			get{ return _A461; }
			set
			{
				this.OnPropertyValueChange("A461");
				this._A461 = value;
			}
		}
		/// <summary>
		/// 被代替标准
		/// </summary>
		[Field("A462")]
		public string A462
		{
			get{ return _A462; }
			set
			{
				this.OnPropertyValueChange("A462");
				this._A462 = value;
			}
		}
		/// <summary>
		/// 发布部门
		/// </summary>
		[Field("ISSUEDEPART")]
		public string ISSUEDEPART
		{
			get{ return _ISSUEDEPART; }
			set
			{
				this.OnPropertyValueChange("ISSUEDEPART");
				this._ISSUEDEPART = value;
			}
		}
		/// <summary>
		/// ICS号
		/// </summary>
		[Field("A404")]
		public string A404
		{
			get{ return _A404; }
			set
			{
				this.OnPropertyValueChange("A404");
				this._A404 = value;
			}
		}
		/// <summary>
		/// 出版语种
		/// </summary>
		[Field("LANGUAGE")]
		public string LANGUAGE
		{
			get{ return _LANGUAGE; }
			set
			{
				this.OnPropertyValueChange("LANGUAGE");
				this._LANGUAGE = value;
			}
		}
		/// <summary>
		/// 版次
		/// </summary>
		[Field("PUBLISHSEQ")]
		public int? PUBLISHSEQ
		{
			get{ return _PUBLISHSEQ; }
			set
			{
				this.OnPropertyValueChange("PUBLISHSEQ");
				this._PUBLISHSEQ = value;
			}
		}
		/// <summary>
		/// 总页数
		/// </summary>
		[Field("A305")]
		public int A305
		{
			get{ return _A305; }
			set
			{
				this.OnPropertyValueChange("A305");
				this._A305 = value;
			}
		}
		/// <summary>
		/// 是否有电子版.1表示有pdf电子文本 0没有
		/// </summary>
		[Field("HAVEPDF")]
		public int HAVEPDF
		{
			get{ return _HAVEPDF; }
			set
			{
				this.OnPropertyValueChange("HAVEPDF");
				this._HAVEPDF = value;
			}
		}
		/// <summary>
		/// 纸质版出版日期
		/// </summary>
		[Field("PAPERPUBLISHDATE")]
		public string PAPERPUBLISHDATE
		{
			get{ return _PAPERPUBLISHDATE; }
			set
			{
				this.OnPropertyValueChange("PAPERPUBLISHDATE");
				this._PAPERPUBLISHDATE = value;
			}
		}
		/// <summary>
		/// 下载打印定价
		/// </summary>
		[Field("DOWNPRICE")]
		public decimal DOWNPRICE
		{
			get{ return _DOWNPRICE; }
			set
			{
				this.OnPropertyValueChange("DOWNPRICE");
				this._DOWNPRICE = value;
			}
		}
		/// <summary>
		/// 是否有彩色图片。0表示无彩色图片
		/// </summary>
		[Field("ISCOLOR")]
		public int? ISCOLOR
		{
			get{ return _ISCOLOR; }
			set
			{
				this.OnPropertyValueChange("ISCOLOR");
				this._ISCOLOR = value;
			}
		}
		/// <summary>
		/// 彩页数
		/// </summary>
		[Field("COLORPAGENUM")]
		public int? COLORPAGENUM
		{
			get{ return _COLORPAGENUM; }
			set
			{
				this.OnPropertyValueChange("COLORPAGENUM");
				this._COLORPAGENUM = value;
			}
		}
		/// <summary>
		/// 书号
		/// </summary>
		[Field("BOOKNO")]
		public string BOOKNO
		{
			get{ return _BOOKNO; }
			set
			{
				this.OnPropertyValueChange("BOOKNO");
				this._BOOKNO = value;
			}
		}
		/// <summary>
		/// 电子版出版日期
		/// </summary>
		[Field("PDFDATE")]
		public string PDFDATE
		{
			get{ return _PDFDATE; }
			set
			{
				this.OnPropertyValueChange("PDFDATE");
				this._PDFDATE = value;
			}
		}
		/// <summary>
		/// 字数。单位：千字
		/// </summary>
		[Field("WORDCOUNT")]
		public int? WORDCOUNT
		{
			get{ return _WORDCOUNT; }
			set
			{
				this.OnPropertyValueChange("WORDCOUNT");
				this._WORDCOUNT = value;
			}
		}
		/// <summary>
		/// 印张
		/// </summary>
		[Field("PRINTNUMBER")]
		public decimal? PRINTNUMBER
		{
			get{ return _PRINTNUMBER; }
			set
			{
				this.OnPropertyValueChange("PRINTNUMBER");
				this._PRINTNUMBER = value;
			}
		}
		/// <summary>
		/// 开本
		/// </summary>
		[Field("FORMAT")]
		public string FORMAT
		{
			get{ return _FORMAT; }
			set
			{
				this.OnPropertyValueChange("FORMAT");
				this._FORMAT = value;
			}
		}
		/// <summary>
		/// 范围
		/// </summary>
		[Field("OWNERDEPT")]
		public string OWNERDEPT
		{
			get{ return _OWNERDEPT; }
			set
			{
				this.OnPropertyValueChange("OWNERDEPT");
				this._OWNERDEPT = value;
			}
		}
		/// <summary>
		/// 起草人
		/// </summary>
		[Field("DRAFTSMAN")]
		public string DRAFTSMAN
		{
			get{ return _DRAFTSMAN; }
			set
			{
				this.OnPropertyValueChange("DRAFTSMAN");
				this._DRAFTSMAN = value;
			}
		}
		/// <summary>
		/// UDC号
		/// </summary>
		[Field("UDCNo")]
		public string UDCNo
		{
			get{ return _UDCNo; }
			set
			{
				this.OnPropertyValueChange("UDCNo");
				this._UDCNo = value;
			}
		}
		/// <summary>
		/// 是否有修改单
		/// </summary>
		[Field("HASMODIFY")]
		public int? HASMODIFY
		{
			get{ return _HASMODIFY; }
			set
			{
				this.OnPropertyValueChange("HASMODIFY");
				this._HASMODIFY = value;
			}
		}
		/// <summary>
		/// 修改单备注
		/// </summary>
		[Field("MODIFYREMARK")]
		public string MODIFYREMARK
		{
			get{ return _MODIFYREMARK; }
			set
			{
				this.OnPropertyValueChange("MODIFYREMARK");
				this._MODIFYREMARK = value;
			}
		}
		/// <summary>
		/// 起草单位
		/// </summary>
		[Field("DRAFTSDEPT")]
		public string DRAFTSDEPT
		{
			get{ return _DRAFTSDEPT; }
			set
			{
				this.OnPropertyValueChange("DRAFTSDEPT");
				this._DRAFTSDEPT = value;
			}
		}
		/// <summary>
		/// 读者对象
		/// </summary>
		[Field("READER")]
		public string READER
		{
			get{ return _READER; }
			set
			{
				this.OnPropertyValueChange("READER");
				this._READER = value;
			}
		}
		/// <summary>
		/// 标准介绍
		/// </summary>
		[Field("INTRODUCTION")]
		public string INTRODUCTION
		{
			get{ return _INTRODUCTION; }
			set
			{
				this.OnPropertyValueChange("INTRODUCTION");
				this._INTRODUCTION = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.QAClassA825up,
				_.QAClassA825,
				_.QAClassA404up,
				_.QAClassA404,
				_.QAHits,
				_.QAComments,
				_.QADownloads,
				_.QAFavorites,
				_.QAPrice,
				_.QAState,
				_.QACreateTime,
				_.QAUpdateTime,
				_.QATestItemCount,
				_.STANDARDID,
				_.STANDCLASS,
				_.STANDTYPE,
				_.A100,
				_.StandPreNo,
				_.A107,
				_.A225,
				_.STANDSTATUS,
				_.REFERSTANDNO,
				_.A825,
				_.A301,
				_.A302,
				_.ADOPTLEVEL,
				_.ADOPTNO,
				_.ADOPTDESC,
				_.DECLAREDATE,
				_.ISSUEDATE,
				_.A205,
				_.MODIDATE,
				_.A200,
				_.COMMITTEEDESC,
				_.SUEDEPART,
				_.A461,
				_.A462,
				_.ISSUEDEPART,
				_.A404,
				_.LANGUAGE,
				_.PUBLISHSEQ,
				_.A305,
				_.HAVEPDF,
				_.PAPERPUBLISHDATE,
				_.DOWNPRICE,
				_.ISCOLOR,
				_.COLORPAGENUM,
				_.BOOKNO,
				_.PDFDATE,
				_.WORDCOUNT,
				_.PRINTNUMBER,
				_.FORMAT,
				_.OWNERDEPT,
				_.DRAFTSMAN,
				_.UDCNo,
				_.HASMODIFY,
				_.MODIFYREMARK,
				_.DRAFTSDEPT,
				_.READER,
				_.INTRODUCTION,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._QAClassA825up,
				this._QAClassA825,
				this._QAClassA404up,
				this._QAClassA404,
				this._QAHits,
				this._QAComments,
				this._QADownloads,
				this._QAFavorites,
				this._QAPrice,
				this._QAState,
				this._QACreateTime,
				this._QAUpdateTime,
				this._QATestItemCount,
				this._STANDARDID,
				this._STANDCLASS,
				this._STANDTYPE,
				this._A100,
				this._StandPreNo,
				this._A107,
				this._A225,
				this._STANDSTATUS,
				this._REFERSTANDNO,
				this._A825,
				this._A301,
				this._A302,
				this._ADOPTLEVEL,
				this._ADOPTNO,
				this._ADOPTDESC,
				this._DECLAREDATE,
				this._ISSUEDATE,
				this._A205,
				this._MODIDATE,
				this._A200,
				this._COMMITTEEDESC,
				this._SUEDEPART,
				this._A461,
				this._A462,
				this._ISSUEDEPART,
				this._A404,
				this._LANGUAGE,
				this._PUBLISHSEQ,
				this._A305,
				this._HAVEPDF,
				this._PAPERPUBLISHDATE,
				this._DOWNPRICE,
				this._ISCOLOR,
				this._COLORPAGENUM,
				this._BOOKNO,
				this._PDFDATE,
				this._WORDCOUNT,
				this._PRINTNUMBER,
				this._FORMAT,
				this._OWNERDEPT,
				this._DRAFTSMAN,
				this._UDCNo,
				this._HASMODIFY,
				this._MODIFYREMARK,
				this._DRAFTSDEPT,
				this._READER,
				this._INTRODUCTION,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Biz_StandardList");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Biz_StandardList", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field QAClassA825up = new Field("QAClassA825up", "Biz_StandardList", "");
            /// <summary>
			/// 中国国家标准CN二级分类
			/// </summary>
			public readonly static Field QAClassA825 = new Field("QAClassA825", "Biz_StandardList", "中国国家标准CN二级分类");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field QAClassA404up = new Field("QAClassA404up", "Biz_StandardList", "");
            /// <summary>
			/// 国际标准ISO二级分类
			/// </summary>
			public readonly static Field QAClassA404 = new Field("QAClassA404", "Biz_StandardList", "国际标准ISO二级分类");
            /// <summary>
			/// 点击/预览数
			/// </summary>
			public readonly static Field QAHits = new Field("QAHits", "Biz_StandardList", "点击/预览数");
            /// <summary>
			/// 评论数
			/// </summary>
			public readonly static Field QAComments = new Field("QAComments", "Biz_StandardList", "评论数");
            /// <summary>
			/// 下载数
			/// </summary>
			public readonly static Field QADownloads = new Field("QADownloads", "Biz_StandardList", "下载数");
            /// <summary>
			/// 收藏数
			/// </summary>
			public readonly static Field QAFavorites = new Field("QAFavorites", "Biz_StandardList", "收藏数");
            /// <summary>
			/// 我们出售的价格
			/// </summary>
			public readonly static Field QAPrice = new Field("QAPrice", "Biz_StandardList", "我们出售的价格");
            /// <summary>
			/// 我们的状态
			/// </summary>
			public readonly static Field QAState = new Field("QAState", "Biz_StandardList", "我们的状态");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field QACreateTime = new Field("QACreateTime", "Biz_StandardList", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field QAUpdateTime = new Field("QAUpdateTime", "Biz_StandardList", "");
            /// <summary>
			/// 检验项目总数
			/// </summary>
			public readonly static Field QATestItemCount = new Field("QATestItemCount", "Biz_StandardList", "检验项目总数");
            /// <summary>
			/// 序列号
			/// </summary>
			public readonly static Field STANDARDID = new Field("STANDARDID", "Biz_StandardList", "序列号");
            /// <summary>
			/// 标准类型。CN-国家标准、QT-行业标准、GW-国外标准、ISO-国际标准、JJ-计量规程规范
			/// </summary>
			public readonly static Field STANDCLASS = new Field("STANDCLASS", "Biz_StandardList", "标准类型。CN-国家标准、QT-行业标准、GW-国外标准、ISO-国际标准、JJ-计量规程规范");
            /// <summary>
			/// 标准属性。STANDCLASS下的二级分类
			/// </summary>
			public readonly static Field STANDTYPE = new Field("STANDTYPE", "Biz_StandardList", "标准属性。STANDCLASS下的二级分类");
            /// <summary>
			/// 标准号
			/// </summary>
			public readonly static Field A100 = new Field("A100", "Biz_StandardList", "标准号");
            /// <summary>
			/// 标准代号
			/// </summary>
			public readonly static Field StandPreNo = new Field("StandPreNo", "Biz_StandardList", "标准代号");
            /// <summary>
			/// 标准编号
			/// </summary>
			public readonly static Field A107 = new Field("A107", "Biz_StandardList", "标准编号");
            /// <summary>
			/// 标准年代号
			/// </summary>
			public readonly static Field A225 = new Field("A225", "Biz_StandardList", "标准年代号");
            /// <summary>
			/// 标准状态
			/// </summary>
			public readonly static Field STANDSTATUS = new Field("STANDSTATUS", "Biz_StandardList", "标准状态");
            /// <summary>
			/// 引用标准号
			/// </summary>
			public readonly static Field REFERSTANDNO = new Field("REFERSTANDNO", "Biz_StandardList", "引用标准号");
            /// <summary>
			/// 中标分类号
			/// </summary>
			public readonly static Field A825 = new Field("A825", "Biz_StandardList", "中标分类号");
            /// <summary>
			/// 中文名称
			/// </summary>
			public readonly static Field A301 = new Field("A301", "Biz_StandardList", "中文名称");
            /// <summary>
			/// 英文名称
			/// </summary>
			public readonly static Field A302 = new Field("A302", "Biz_StandardList", "英文名称");
            /// <summary>
			/// 采标程度
			/// </summary>
			public readonly static Field ADOPTLEVEL = new Field("ADOPTLEVEL", "Biz_StandardList", "采标程度");
            /// <summary>
			/// 采标号
			/// </summary>
			public readonly static Field ADOPTNO = new Field("ADOPTNO", "Biz_StandardList", "采标号");
            /// <summary>
			/// 采标名称
			/// </summary>
			public readonly static Field ADOPTDESC = new Field("ADOPTDESC", "Biz_StandardList", "采标名称");
            /// <summary>
			/// 公告日期
			/// </summary>
			public readonly static Field DECLAREDATE = new Field("DECLAREDATE", "Biz_StandardList", "公告日期");
            /// <summary>
			/// 首发日期.原来的发布日期等于现在的首发日期
			/// </summary>
			public readonly static Field ISSUEDATE = new Field("ISSUEDATE", "Biz_StandardList", "首发日期.原来的发布日期等于现在的首发日期");
            /// <summary>
			/// 实施日期.原来的修订日期等于现在的发布日期
			/// </summary>
			public readonly static Field A205 = new Field("A205", "Biz_StandardList", "实施日期.原来的修订日期等于现在的发布日期");
            /// <summary>
			/// 发布日期.1900-1-1表示空的
			/// </summary>
			public readonly static Field MODIDATE = new Field("MODIDATE", "Biz_StandardList", "发布日期.1900-1-1表示空的");
            /// <summary>
			/// 作废标记.0表示未作废
			/// </summary>
			public readonly static Field A200 = new Field("A200", "Biz_StandardList", "作废标记.0表示未作废");
            /// <summary>
			/// 标准化技术委员会.即归口单位
			/// </summary>
			public readonly static Field COMMITTEEDESC = new Field("COMMITTEEDESC", "Biz_StandardList", "标准化技术委员会.即归口单位");
            /// <summary>
			/// 提出部门
			/// </summary>
			public readonly static Field SUEDEPART = new Field("SUEDEPART", "Biz_StandardList", "提出部门");
            /// <summary>
			/// 代替标准
			/// </summary>
			public readonly static Field A461 = new Field("A461", "Biz_StandardList", "代替标准");
            /// <summary>
			/// 被代替标准
			/// </summary>
			public readonly static Field A462 = new Field("A462", "Biz_StandardList", "被代替标准");
            /// <summary>
			/// 发布部门
			/// </summary>
			public readonly static Field ISSUEDEPART = new Field("ISSUEDEPART", "Biz_StandardList", "发布部门");
            /// <summary>
			/// ICS号
			/// </summary>
			public readonly static Field A404 = new Field("A404", "Biz_StandardList", "ICS号");
            /// <summary>
			/// 出版语种
			/// </summary>
			public readonly static Field LANGUAGE = new Field("LANGUAGE", "Biz_StandardList", "出版语种");
            /// <summary>
			/// 版次
			/// </summary>
			public readonly static Field PUBLISHSEQ = new Field("PUBLISHSEQ", "Biz_StandardList", "版次");
            /// <summary>
			/// 总页数
			/// </summary>
			public readonly static Field A305 = new Field("A305", "Biz_StandardList", "总页数");
            /// <summary>
			/// 是否有电子版.1表示有pdf电子文本 0没有
			/// </summary>
			public readonly static Field HAVEPDF = new Field("HAVEPDF", "Biz_StandardList", "是否有电子版.1表示有pdf电子文本 0没有");
            /// <summary>
			/// 纸质版出版日期
			/// </summary>
			public readonly static Field PAPERPUBLISHDATE = new Field("PAPERPUBLISHDATE", "Biz_StandardList", "纸质版出版日期");
            /// <summary>
			/// 下载打印定价
			/// </summary>
			public readonly static Field DOWNPRICE = new Field("DOWNPRICE", "Biz_StandardList", "下载打印定价");
            /// <summary>
			/// 是否有彩色图片。0表示无彩色图片
			/// </summary>
			public readonly static Field ISCOLOR = new Field("ISCOLOR", "Biz_StandardList", "是否有彩色图片。0表示无彩色图片");
            /// <summary>
			/// 彩页数
			/// </summary>
			public readonly static Field COLORPAGENUM = new Field("COLORPAGENUM", "Biz_StandardList", "彩页数");
            /// <summary>
			/// 书号
			/// </summary>
			public readonly static Field BOOKNO = new Field("BOOKNO", "Biz_StandardList", "书号");
            /// <summary>
			/// 电子版出版日期
			/// </summary>
			public readonly static Field PDFDATE = new Field("PDFDATE", "Biz_StandardList", "电子版出版日期");
            /// <summary>
			/// 字数。单位：千字
			/// </summary>
			public readonly static Field WORDCOUNT = new Field("WORDCOUNT", "Biz_StandardList", "字数。单位：千字");
            /// <summary>
			/// 印张
			/// </summary>
			public readonly static Field PRINTNUMBER = new Field("PRINTNUMBER", "Biz_StandardList", "印张");
            /// <summary>
			/// 开本
			/// </summary>
			public readonly static Field FORMAT = new Field("FORMAT", "Biz_StandardList", "开本");
            /// <summary>
			/// 范围
			/// </summary>
			public readonly static Field OWNERDEPT = new Field("OWNERDEPT", "Biz_StandardList", "范围");
            /// <summary>
			/// 起草人
			/// </summary>
			public readonly static Field DRAFTSMAN = new Field("DRAFTSMAN", "Biz_StandardList", "起草人");
            /// <summary>
			/// UDC号
			/// </summary>
			public readonly static Field UDCNo = new Field("UDCNo", "Biz_StandardList", "UDC号");
            /// <summary>
			/// 是否有修改单
			/// </summary>
			public readonly static Field HASMODIFY = new Field("HASMODIFY", "Biz_StandardList", "是否有修改单");
            /// <summary>
			/// 修改单备注
			/// </summary>
			public readonly static Field MODIFYREMARK = new Field("MODIFYREMARK", "Biz_StandardList", "修改单备注");
            /// <summary>
			/// 起草单位
			/// </summary>
			public readonly static Field DRAFTSDEPT = new Field("DRAFTSDEPT", "Biz_StandardList", "起草单位");
            /// <summary>
			/// 读者对象
			/// </summary>
			public readonly static Field READER = new Field("READER", "Biz_StandardList", "读者对象");
            /// <summary>
			/// 标准介绍
			/// </summary>
			public readonly static Field INTRODUCTION = new Field("INTRODUCTION", "Biz_StandardList", "标准介绍");
        }
        #endregion
	}
}