//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Standard.DataModel
{
    /// <summary>
    /// 实体类BizUser。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Biz_User")]
    [Serializable]
    public partial class BizUser : Entity
    {
        #region Model
		private Guid _Id;
		private string _Account;
		private string _Pwd;
		private string _RealName;
		private string _NickName;
		private string _Phone;
		private int _State;
		private string _Avatar;
		private string _Remark;
		private int? _VipLevel;
		private string _RegIp;
		private DateTime _CreateTime;

		/// <summary>
		/// 
		/// </summary>
		[Field("Id")]
		public Guid Id
		{
			get{ return _Id; }
			set
			{
				this.OnPropertyValueChange("Id");
				this._Id = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Account")]
		public string Account
		{
			get{ return _Account; }
			set
			{
				this.OnPropertyValueChange("Account");
				this._Account = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Pwd")]
		public string Pwd
		{
			get{ return _Pwd; }
			set
			{
				this.OnPropertyValueChange("Pwd");
				this._Pwd = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RealName")]
		public string RealName
		{
			get{ return _RealName; }
			set
			{
				this.OnPropertyValueChange("RealName");
				this._RealName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("NickName")]
		public string NickName
		{
			get{ return _NickName; }
			set
			{
				this.OnPropertyValueChange("NickName");
				this._NickName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Phone")]
		public string Phone
		{
			get{ return _Phone; }
			set
			{
				this.OnPropertyValueChange("Phone");
				this._Phone = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("State")]
		public int State
		{
			get{ return _State; }
			set
			{
				this.OnPropertyValueChange("State");
				this._State = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Avatar")]
		public string Avatar
		{
			get{ return _Avatar; }
			set
			{
				this.OnPropertyValueChange("Avatar");
				this._Avatar = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("Remark")]
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange("Remark");
				this._Remark = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("VipLevel")]
		public int? VipLevel
		{
			get{ return _VipLevel; }
			set
			{
				this.OnPropertyValueChange("VipLevel");
				this._VipLevel = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("RegIp")]
		public string RegIp
		{
			get{ return _RegIp; }
			set
			{
				this.OnPropertyValueChange("RegIp");
				this._RegIp = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CreateTime")]
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange("CreateTime");
				this._CreateTime = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.Account,
				_.Pwd,
				_.RealName,
				_.NickName,
				_.Phone,
				_.State,
				_.Avatar,
				_.Remark,
				_.VipLevel,
				_.RegIp,
				_.CreateTime,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._Account,
				this._Pwd,
				this._RealName,
				this._NickName,
				this._Phone,
				this._State,
				this._Avatar,
				this._Remark,
				this._VipLevel,
				this._RegIp,
				this._CreateTime,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "Biz_User");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Biz_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Account = new Field("Account", "Biz_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Pwd = new Field("Pwd", "Biz_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field RealName = new Field("RealName", "Biz_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field NickName = new Field("NickName", "Biz_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Phone = new Field("Phone", "Biz_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State", "Biz_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Avatar = new Field("Avatar", "Biz_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Remark = new Field("Remark", "Biz_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field VipLevel = new Field("VipLevel", "Biz_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field RegIp = new Field("RegIp", "Biz_User", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime", "Biz_User", "");
        }
        #endregion
	}
}